// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWotx3RiENR60asWhfhp2Xqud5R2ckc4s',
    appId: '1:499118169985:web:528ad3bdb550ca1bda1280',
    messagingSenderId: '499118169985',
    projectId: 'xpense-flutter-web',
    authDomain: 'xpense-flutter-web.firebaseapp.com',
    storageBucket: 'xpense-flutter-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAl0awQjIQsNgfGKHqmio_3dOwhWV-6s',
    appId: '1:499118169985:android:c163e0d529f2d5e2da1280',
    messagingSenderId: '499118169985',
    projectId: 'xpense-flutter-web',
    storageBucket: 'xpense-flutter-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyXOGuuLkkmBPmWOuKk0NDWAC93ZQLes',
    appId: '1:499118169985:ios:63f2af3e31b25625da1280',
    messagingSenderId: '499118169985',
    projectId: 'xpense-flutter-web',
    storageBucket: 'xpense-flutter-web.firebasestorage.app',
    iosBundleId: 'com.example.xpense',
  );
}
